#!/usr/bin/env node
// WCAG remediation applier — applies a remediation PLAN (computed by
// wcag-pass.ts from the contrast statistics + the TS policy layer) to a
// template directory:
//
//   node pipeline/scripts/wcag/remediate.ts \
//       (--plan wcag-remediation-plan.json | --choice wcag-choice.json) \
//       --template-dir <dir>
//
// POLICY: the automatic path (--plan) applies COLORS ONLY — the plan's rules
// are within-bar recolors. Halo / recolor+backing recommendations are NEVER
// auto-applied; they arrive as plan notes and surface as CSS comments for human
// review. A USER-CHOSEN option (--choice) is different: the click/chat pick IS
// the human approval, so chosen options apply beyond colours-only (shadow /
// outline / background). The applier makes no policy decisions of its own.
//
// Outputs a SIBLING runnable template dir `<dir>.wcag-remediated/` (source dir
// is never touched; sibling depth keeps relative asset paths resolving —
// veed-engine-cli only accepts template directories) containing:
//   - template.wv|template.html — copy with an injected
//     `<style id="wcag-remediation">` block (re-running REPLACES the block)
//   - wcag-remediation.css — the same rules as a standalone inspectable file,
//     with per-rule evidence comments and a comment for every recommendation
//     that could NOT be applied
//   - every other file of the source dir, copied as-is
//
// The injected block is appended LAST inside <head>, so its same-specificity
// rules win the cascade's source-order tie-break against author declarations.
//
// Runs under plain `node` (native .ts type-stripping, >=22.18) — no tsx.

import { cpSync, existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import process from "node:process";

import { DEFAULT_SHADOW_RECIPE, parseChoiceFile, type ChoiceFile } from "./wcag-choice.ts";

export const REMEDIATION_BLOCK_ID = "wcag-remediation";

/** sRGB bytes → lowercase 6-digit CSS hex. Exported as the SSOT formatter —
 * tests must import this, never mirror the formula. */
export const hex = (c: { r: number; g: number; b: number }): string =>
  "#" + [c.r, c.g, c.b].map((v) => v.toString(16).padStart(2, "0")).join("");

/** One applied colour rule. `massPct` / `worstRatio` are evidence for the CSS
 * comment (estimated failing mass %, worst per-cluster ratio of the new colour). */
export interface PlanRule {
  selector: string;
  hex: string;
  massPct: number;
  worstRatio: number;
}

/** The applier's whole input contract. `notes` carry every recommendation that
 * is NOT applied (halo/backing/no-colour/indeterminate), verbatim from the
 * gate's dispositions — emitted as comments so nothing failing goes unlisted. */
export interface RemediationPlan {
  level: "AA";
  rules: PlanRule[];
  notes: string[];
}

export function parsePlanFile(raw: unknown): RemediationPlan {
  const p = raw as RemediationPlan;
  if (!p || p.level !== "AA" || !Array.isArray(p.rules) || !Array.isArray(p.notes)) {
    throw new Error("wcag-remediation-plan: expected { level: 'AA', rules: [], notes: [] }");
  }
  for (const r of p.rules) {
    if (!r.selector || !/^#[0-9a-f]{6}$/.test(r.hex)) {
      throw new Error(`wcag-remediation-plan: bad rule ${JSON.stringify(r)} (need selector + 6-digit lowercase hex)`);
    }
  }
  return p;
}

/** The full remediation stylesheet for a plan. Colors only. */
export function buildPlanCss(plan: RemediationPlan): string {
  const lines: string[] = [
    `/* WCAG remediation — generated by pipeline/scripts/wcag/remediate.ts`,
    `   level ${plan.level}, automatic hue-preserving colour set, colours only.`,
    `   Evidence per rule below; unapplied recommendations left as comments. */`,
  ];
  for (const r of plan.rules) {
    lines.push(
      `/* ${r.selector}: recolor (estimated failure ${r.massPct.toFixed(1)}%, worst ${r.worstRatio.toFixed(2)}:1) */`,
      `${r.selector} { color: ${r.hex}; }`,
    );
  }
  for (const n of plan.notes) {
    lines.push(`/* not applied — ${n} */`);
  }
  return lines.join("\n") + "\n";
}

/**
 * Inject (or REPLACE — idempotent) the remediation style block. Placed before
 * `</head>` so it follows the author's styles in the cascade; falls back to
 * before `</body>`, else appends.
 */
export function injectRemediationBlock(html: string, css: string): string {
  const block = `<style id="${REMEDIATION_BLOCK_ID}">\n${css}</style>`;
  const existing = new RegExp(
    `<style id="${REMEDIATION_BLOCK_ID}">[\\s\\S]*?</style>`,
  );
  if (existing.test(html)) return html.replace(existing, block);
  for (const anchor of ["</head>", "</body>"]) {
    const i = html.indexOf(anchor);
    if (i >= 0) return html.slice(0, i) + block + "\n" + html.slice(i);
  }
  return html + "\n" + block + "\n";
}

/**
 * The remediation stylesheet for USER-CHOSEN options (the --choice path). The
 * click in the studio (or the chat pick) IS the human approval, so this applies
 * chosen options beyond colours-only: colour -> `color`, shadow ->
 * `text-shadow` stack, outline -> `-webkit-text-stroke`, background ->
 * `color` + `background-color`. Selectors are carried in each entry, so no
 * re-derivation happens here.
 */
export function buildChoiceCss(file: ChoiceFile): string {
  const lines: string[] = [
    `/* WCAG remediation — generated by pipeline/scripts/wcag/remediate.ts --choice.`,
    `   User-chosen via the studio or chat (the pick is the approval; shadow/outline/`,
    `   background are unlocked by an explicit choice — colours-only is the no-choice default). */`,
  ];
  for (const c of file.chosen) {
    // A heterogeneous group (outlier shadow/background) carries a per-selector
    // `split`; otherwise the single `selector` is the one part.
    const parts =
      c.split && c.split.length > 0
        ? c.split
        : c.selector
          ? [{ selector: c.selector, hex: c.hex, backingHex: c.backingHex }]
          : null;
    if (!parts) throw new Error(`wcag-choice: ${c.level} ${c.group} ${c.kind} has no selector — cannot apply`);
    lines.push(
      `/* ${parts[0].selector}: user-chosen — ${c.level} ${c.group} ${c.kind}${c.split ? ` (${c.split.length}-way split)` : ""} */`,
    );
    for (const p of parts) {
      if (c.kind === "colour") {
        lines.push(`${p.selector} { color: ${p.hex}; }`);
      } else if (c.kind === "shadow") {
        // Soft-shadow STACK from the solved recipe: `layers` centered `0 0 {blur}px`
        // shadows, same colour at the modelled coverage alpha (0.85 -> hex d9).
        const { layers, blur } = c.recipe ?? DEFAULT_SHADOW_RECIPE;
        const stack = Array.from({ length: layers }, () => `0 0 ${blur}px ${p.hex}d9`).join(", ");
        lines.push(`${p.selector} { text-shadow: ${stack}; }`);
      } else if (c.kind === "outline") {
        lines.push(`${p.selector} { -webkit-text-stroke: 1.5px ${p.hex}; }`);
      } else {
        lines.push(`${p.selector} { color: ${p.hex}; background-color: ${p.backingHex}; }`);
      }
    }
  }
  return lines.join("\n") + "\n";
}

function usage(msg?: string): never {
  if (msg) console.error(`remediate: ${msg}`);
  console.error(
    "usage: node pipeline/scripts/wcag/remediate.ts (--plan <wcag-remediation-plan.json> | --choice <wcag-choice.json>) --template-dir <dir>",
  );
  process.exit(2);
}

function main(): void {
  const args = process.argv.slice(2);
  let planPath = "";
  let choicePath = "";
  let templateDir = "";
  for (let i = 0; i < args.length; i++) {
    const next = () => {
      const v = args[++i];
      if (v === undefined || v === "") usage(`${args[i - 1]} requires a value`);
      return v;
    };
    switch (args[i]) {
      case "--plan": planPath = next(); break;
      case "--choice": choicePath = next(); break;
      case "--template-dir": templateDir = next(); break;
      default: usage(`unknown argument '${args[i]}'`);
    }
  }
  if (!templateDir) usage("--template-dir is required");
  if (planPath && choicePath) usage("--plan and --choice are mutually exclusive");
  if (!planPath && !choicePath) usage("one of --plan or --choice is required");

  const css = choicePath
    ? buildChoiceCss(parseChoiceFile(JSON.parse(readFileSync(choicePath, "utf8"))))
    : buildPlanCss(parsePlanFile(JSON.parse(readFileSync(planPath, "utf8"))));

  const srcDir = resolve(templateDir);
  const templateName = ["template.wv", "template.html"].find((n) =>
    existsSync(join(srcDir, n)),
  );
  if (!templateName) usage(`no template.wv or template.html in ${srcDir}`);

  const outDir = join(dirname(srcDir), `${basename(srcDir)}.wcag-remediated`);
  rmSync(outDir, { recursive: true, force: true });
  cpSync(srcDir, outDir, { recursive: true });

  const html = readFileSync(join(srcDir, templateName), "utf8");
  writeFileSync(join(outDir, templateName), injectRemediationBlock(html, css));
  writeFileSync(join(outDir, "wcag-remediation.css"), css);

  const ruleCount = (css.match(/^\S.* \{ /gm) ?? []).length;
  const noteCount = (css.match(/not applied — /g) ?? []).length;
  const how = choicePath ? "user-chosen rule(s) applied" : "color rule(s) applied";
  console.log(
    `wcag-remediation: ${ruleCount} ${how}, ${noteCount} recommendation(s) left for human review -> ${outDir}`,
  );
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(import.meta.filename)) {
  main();
}
